services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Backend/db:/docker-entrypoint-initdb.d

  backend:
    build: ./Backend
    ports:
      - "3002:3002"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PW: ${PG_PW}
    depends_on:
      - postgres

  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: